name: 🤖 Auto approve and merge Dependabot pull requests

on: pull_request_target

jobs:
  # Auto-approve dependabot PRs
  # https://github.com/marketplace/actions/auto-approve
  auto-approve-dependabot-pr:
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v4

  # Auto-merge dependabot PRs
  # https://github.com/marketplace/actions/simple-auto-merge
  auto-merge-dependabot-pr:
    if: github.actor == 'dependabot[bot]'
    needs: auto-approve-dependabot-pr
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: kenhowardpdx/auto-merge-action@v1
